spring:
  application:
    name: gatewaySpring

  cloud:
    gateway:
      routes:
        - id: route1
          uri: http://127.0.0.1:8081/
          predicates:
            - Path=/api/v1/categories
          filters:
            - TokenRelay
  security:
    oauth2:
      client:
        registration:
          my-provider:
            provider: my-provider
            client-id: "oidc-client"
            client-secret: "secret"
            authorization-grant-type: authorization_code
            redirect-uri: http://127.0.0.1:1680/login/oauth2/code/oidc-client
            client-authentication-method:
              - client_secret_post
              - client_secret_basic
            scope:
              - openid
              - profile
              - email
              - address
        provider:
          my-provider:
            authorization-uri: http://127.0.0.1:8080/identity/oauth2/authorize
            token-uri: http://127.0.0.1:8080/identity/oauth2/token
            user-info-uri: http://127.0.0.1:8080/identity/oauth2/userinfo
            issuer-uri: http://127.0.0.1:8080/identity
server:
  port: 1680
logging:
  level:
    org:
      springframework:
        cloud:
          gateway: DEBUG
